# Data collection

In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
# Design family and directory
fam = '03-ext'
base_dir = r'D:\Entwicklungen\share\DataScienceProject'

In [7]:
# Import of parameters and design points
all_data = {}
fam_dir = os.path.join(base_dir, fam, 'data-' + fam)
ft_param_path = os.path.join(base_dir, 'sep24_cds_int_us-welding', 'ft_files', str(fam) + '_coll_parameters.ft')
all_data[fam] = {}

# Column names and widths
ident_cols = ['dp_no', 'mode_no', 'freq', 'rel_dev', 'mean_in_disp', 'mean_out_disp', 'mode_gain', 'mode_mac']
mode_cols = ['mode_no', 'freq', 'rel_dev', 'mean_in_disp', 'mean_out_disp', 'mode_gain', 'mode_mac']
node_cols = ['node_no', 'x_coord', 'y_coord', 'z_coord']
def_cols = ['mode' + str(x) for x in range(1, 101)]
ident_wd = [8, 12, 15, 15, 15, 15, 15, 15]
mode_wd = [8, 15, 15, 15, 15, 15, 15]
node_wd = [10, 20, 20, 20]
def_wd = [20 for x in range(100)]

# Subset of modes for each design family
fam_mode_subset = {'01': range(1, 14), '02': range(17, 31), '03': range(25, 101), '03-ext': range(25, 101)}
lst_modes = ['mode' + str(x) for x in fam_mode_subset[fam]]

# Geometrical parameters  
all_data[fam]['parameters'] = {}
params_file = os.path.join(fam_dir, 'design-points-' + fam + '.csv')
df_param = pd.read_csv(params_file, sep=';')

# Identification of the longitudinal mode
ident_file = os.path.join(fam_dir, 'mode-ident-full-' + fam + '.dat')
df_ident = pd.read_fwf(ident_file, widths=ident_wd, comment='#', names=ident_cols)

# Merge both DataFrames
all_data[fam]['parameters'] = pd.merge(df_param, df_ident, how='outer', on='dp_no')

# List of design points
lst_dp = df_param['dp_no'].to_list()

# Export DataFrame as binary file
all_data[fam]['parameters'].to_feather(ft_param_path)

In [8]:
all_data[fam]['parameters']

,dp_no,dim_x,dim_y,dim_z,nb_slots_x,slot_x_length,slot_x_distance,nb_slots_z,slot_z_length,slot_z_distance,...,cut_z_start,cut_z_end,cut_z_depth,mode_no,freq,rel_dev,mean_in_disp,mean_out_disp,mode_gain,mode_mac
0,13000,146.25,117.38,235.46,4,79.173,42.606,2,78.875,58.737,...,23.050,63.348,1.10350,77.0,19804.971,1.05774,-0.254,0.360,1.41582,0.756804
1,13001,130.53,118.96,226.27,4,82.404,54.922,2,80.518,52.995,...,32.987,66.038,4.57780,76.0,19669.124,0.44016,-0.383,0.398,1.03847,0.934646
2,13002,107.37,115.60,231.00,4,74.852,43.698,2,76.750,62.249,...,42.869,58.647,0.64307,71.0,19773.135,0.61991,-0.401,0.374,0.93259,0.922389
3,13003,116.22,123.67,257.89,4,75.324,46.253,2,79.942,65.116,...,37.865,56.437,0.31975,70.0,18595.310,0.49367,-0.374,0.368,0.98276,0.922391
4,13004,127.53,124.55,229.44,4,78.681,46.044,2,79.512,61.595,...,43.168,60.116,2.38490,69.0,18257.884,0.23684,0.346,-0.378,1.09316,0.929686
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,14995,161.27,117.39,204.33,4,81.443,44.140,2,75.160,60.446,...,31.490,69.296,0.26390,78.0,19917.584,1.93442,-0.405,0.301,0.74305,0.742305
1996,14996,175.54,124.19,242.70,4,80.506,50.429,2,76.709,61.121,...,33.181,63.036,1.13220,79.0,19047.397,1.48299,0.403,-0.249,0.61718,0.798798
1997,14997,117.25,124.30,204.04,4,77.569,42.343,2,82.824,63.187,...,23.684,63.068,1.54320,68.0,18122.820,0.23480,0.413,-0.419,1.01581,0.966862
1998,14998,137.78,122.21,245.39,4,75.404,50.357,2,81.691,59.562,...,42.926,65.017,0.81244,73.0,19245.938,0.21864,0.335,-0.345,1.03126,0.967012
1999,14999,157.36,120.66,241.65,4,81.503,51.388,2,77.271,50.748,...,33.051,61.728,2.18510,79.0,19579.764,0.73410,-0.393,0.309,0.78691,0.955312

In [ ]:
# Import of modes, nodes and displacements for each design point
all_data[fam]['modes'] = pd.DataFrame()
all_data[fam]['nodes'] = pd.DataFrame()
all_data[fam]['defs'] = pd.DataFrame()
ft_mode_path = os.path.join(base_dir, 'sep24_cds_int_us-welding', 'ft_files', str(fam) + '_coll_modes.ft')
ft_node_path = os.path.join(base_dir, 'sep24_cds_int_us-welding', 'ft_files', str(fam) + '_coll_nodes.ft')
ft_defs_path = os.path.join(base_dir, 'sep24_cds_int_us-welding', 'ft_files', str(fam) + '_coll_defs.ft')

#for dp in [13000, 13001, 13002]:
for dp in lst_dp:
        
    print ('. Design point', str(dp), 'of', str(lst_dp[-1]))

    # Mode file
    mode_file = 'tbl-modes-' + str(dp) + '.dat'
    mode_path = os.path.join(fam_dir, 'modes', mode_file)

    if os.path.exists(mode_path):

        df_nodes = pd.read_fwf(mode_path, widths=mode_wd, comment='#', names=mode_cols)

        # Add design point as column
        n_modes = len(df_nodes)   # Number of modes
        df_nodes.insert(0, 'dp_no', pd.Series(dp*np.ones(n_modes), index=df_nodes.index))
        
        # Add subset of modes to dictionary
        all_data[fam]['modes'] = pd.concat([all_data[fam]['modes'], df_nodes[df_nodes['mode_no'].isin(fam_mode_subset[fam])]], axis=0, ignore_index=True)


    # Node and displacement files
    node_file = 'tbl-nodes-' + str(dp) + '.dat'
    node_path = os.path.join(fam_dir, 'nodes', node_file)
    def_file = 'tbl-def-y-' + str(dp) + '.dat'
    def_path = os.path.join(fam_dir, 'defs', def_file)

    if (os.path.exists(node_path) & os.path.exists(def_path)):

        # ---
        # Node file
        df_nodes = pd.read_fwf(node_path, widths=node_wd, comment='#', names=node_cols)

        # Write design point as foreign key
        node_list = df_nodes['node_no'].astype(int).to_list()
        df_nodes = pd.DataFrame({'dp_no': dp}, index=df_nodes.index).join(df_nodes)

        # Add subset of modes to dictionary
        all_data[fam]['nodes'] = pd.concat([all_data[fam]['nodes'], df_nodes], axis=0, ignore_index=True)

        # ---
        # Displacement file
        df_defs = pd.read_fwf(def_path, widths=def_wd, header=None, names=def_cols)

        # Keep the displacements of the subset of modes only
        df_defs = df_defs[lst_modes]

        # Write displacements and add "node_no", "dp_no" as foreign keys
        df_defs = pd.DataFrame({'node_no': node_list}, index=df_defs.index).join(df_defs)
        df_defs = pd.DataFrame({'dp_no': dp}, index=df_defs.index).join(df_defs)

        # Add displacements to dictionary
        all_data[fam]['defs'] = pd.concat([all_data[fam]['defs'], df_defs], axis=0, ignore_index=True)


# Specify data types
all_data[fam]['modes'] = all_data[fam]['modes'].astype({'dp_no': 'int', 'mode_no': 'int'})
all_data[fam]['modes']['rel_dev'] = pd.to_numeric(all_data[fam]['modes']['rel_dev'], errors='coerce')
all_data[fam]['nodes'] = all_data[fam]['nodes'].astype({'dp_no': 'int', 'node_no': 'int'})

# Set node coordinates in milimeters
all_data[fam]['nodes'][['x_coord', 'y_coord', 'z_coord']] = all_data[fam]['nodes'][['x_coord', 'y_coord', 'z_coord']]*1e3

# Export DataFrames as binary file
all_data[fam]['modes'].to_feather(ft_mode_path)
all_data[fam]['nodes'].to_feather(ft_node_path)
all_data[fam]['defs'].to_feather(ft_defs_path)

. Design point 13000 of 14999
. Design point 13001 of 14999
. Design point 13002 of 14999
. Design point 13003 of 14999
. Design point 13004 of 14999
. Design point 13005 of 14999
. Design point 13006 of 14999
. Design point 13007 of 14999
. Design point 13008 of 14999
. Design point 13009 of 14999
. Design point 13010 of 14999
. Design point 13011 of 14999
. Design point 13012 of 14999
. Design point 13013 of 14999
. Design point 13014 of 14999
. Design point 13015 of 14999
. Design point 13016 of 14999
. Design point 13017 of 14999
. Design point 13018 of 14999
. Design point 13019 of 14999
. Design point 13020 of 14999
. Design point 13021 of 14999
. Design point 13022 of 14999
. Design point 13023 of 14999
. Design point 13024 of 14999
. Design point 13025 of 14999
. Design point 13026 of 14999
. Design point 13027 of 14999
. Design point 13028 of 14999
. Design point 13029 of 14999
. Design point 13030 of 14999
. Design point 13031 of 14999
. Design point 13032 of 14999
. Design point 13033 of 14999
. Design point 13034 of 14999
. Design point 13035 of 14999
. Design point 13036 of 14999
. Design point 13037 of 14999
. Design point 13038 of 14999
. Design point 13039 of 14999
. Design point 13040 of 14999
. Design point 13041 of 14999
. Design point 13042 of 14999
. Design point 13043 of 14999
. Design point 13044 of 14999
. Design point 13045 of 14999
. Design point 13046 of 14999
. Design point 13047 of 14999
. Design point 13048 of 14999
. Design point 13049 of 14999
. Design point 13050 of 14999
. Design point 13051 of 14999
. Design point 13052 of 14999
. Design point 13053 of 14999
. Design point 13054 of 14999
. Design point 13055 of 14999
. Design point 13056 of 14999
. Design point 13057 of 14999
. Design point 13058 of 14999
. Design point 13059 of 14999
. Design point 13060 of 14999
. Design point 13061 of 14999
. Design point 13062 of 14999
. Design point 13063 of 14999
. Design point 13064 of 14999
. Design point 13065 of 14999
. Design point 13066 of 14999
. Design point 13067 of 14999
. Design point 13068 of 14999
. Design point 13069 of 14999
. Design point 13070 of 14999
. Design point 13071 of 14999
. Design point 13072 of 14999
. Design point 13073 of 14999
. Design point 13074 of 14999
. Design point 13075 of 14999
. Design point 13076 of 14999
. Design point 13077 of 14999
. Design point 13078 of 14999
. Design point 13079 of 14999
. Design point 13080 of 14999
. Design point 13081 of 14999
. Design point 13082 of 14999
. Design point 13083 of 14999
. Design point 13084 of 14999
. Design point 13085 of 14999
. Design point 13086 of 14999
. Design point 13087 of 14999
. Design point 13088 of 14999
. Design point 13089 of 14999
. Design point 13090 of 14999
. Design point 13091 of 14999
. Design point 13092 of 14999
. Design point 13093 of 14999
. Design point 13094 of 14999
. Design point 13095 of 14999
. Design point 13096 of 14999
. Design point 13097 of 14999
. Design point 13098 of 14999
. Design point 13099 of 14999
. Design point 13100 of 14999
. Design point 13101 of 14999
. Design point 13102 of 14999
. Design point 13103 of 14999
. Design point 13104 of 14999
. Design point 13105 of 14999
. Design point 13106 of 14999
. Design point 13107 of 14999
. Design point 13108 of 14999
. Design point 13109 of 14999
. Design point 13110 of 14999
. Design point 13111 of 14999
. Design point 13112 of 14999
. Design point 13113 of 14999
. Design point 13114 of 14999
. Design point 13115 of 14999
. Design point 13116 of 14999
. Design point 13117 of 14999
. Design point 13118 of 14999
. Design point 13119 of 14999
. Design point 13120 of 14999
. Design point 13121 of 14999
. Design point 13122 of 14999
. Design point 13123 of 14999
. Design point 13124 of 14999
. Design point 13125 of 14999
. Design point 13126 of 14999
. Design point 13127 of 14999
. Design point 13128 of 14999
. Design point 13129 of 14999
. Design point 13130 of 14999
. Design point 13131 of 14999
. Design point 13132 of 14999
. Design point 13133 of 14999
. Design point 13134 of 14999
. Design point 13135 of 14999
. Design point 13136 of 14999
. Design point 13137 of 14999
. Design point 13138 of 14999
. Design point 13139 of 14999
. Design point 13140 of 14999
. Design point 13141 of 14999
. Design point 13142 of 14999
. Design point 13143 of 14999
. Design point 13144 of 14999
. Design point 13145 of 14999
. Design point 13146 of 14999
. Design point 13147 of 14999
. Design point 13148 of 14999
. Design point 13149 of 14999
. Design point 13150 of 14999
. Design point 13151 of 14999
. Design point 13152 of 14999
. Design point 13153 of 14999
. Design point 13154 of 14999
. Design point 13155 of 14999
. Design point 13156 of 14999
. Design point 13157 of 14999
. Design point 13158 of 14999
. Design point 13159 of 14999
. Design point 13160 of 14999
. Design point 13161 of 14999
. Design point 13162 of 14999
. Design point 13163 of 14999
. Design point 13164 of 14999
. Design point 13165 of 14999
. Design point 13166 of 14999
. Design point 13167 of 14999
. Design point 13168 of 14999
. Design point 13169 of 14999
. Design point 13170 of 14999
. Design point 13171 of 14999
. Design point 13172 of 14999
. Design point 13173 of 14999
. Design point 13174 of 14999
. Design point 13175 of 14999
. Design point 13176 of 14999
. Design point 13177 of 14999
. Design point 13178 of 14999
. Design point 13179 of 14999
. Design point 13180 of 14999
. Design point 13181 of 14999
. Design point 13182 of 14999
. Design point 13183 of 14999
. Design point 13184 of 14999
. Design point 13185 of 14999
. Design point 13186 of 14999
. Design point 13187 of 14999
. Design point 13188 of 14999
. Design point 13189 of 14999
. Design point 13190 of 14999
. Design point 13191 of 14999
. Design point 13192 of 14999
. Design point 13193 of 14999
. Design point 13194 of 14999
. Design point 13195 of 14999
. Design point 13196 of 14999
. Design point 13197 of 14999
. Design point 13198 of 14999
. Design point 13199 of 14999
. Design point 13200 of 14999
. Design point 13201 of 14999
. Design point 13202 of 14999
. Design point 13203 of 14999
. Design point 13204 of 14999
. Design point 13205 of 14999
. Design point 13206 of 14999
. Design point 13207 of 14999
. Design point 13208 of 14999
. Design point 13209 of 14999
. Design point 13210 of 14999
. Design point 13211 of 14999
. Design point 13212 of 14999
. Design point 13213 of 14999
. Design point 13214 of 14999
. Design point 13215 of 14999
. Design point 13216 of 14999
. Design point 13217 of 14999
. Design point 13218 of 14999
. Design point 13219 of 14999
. Design point 13220 of 14999
. Design point 13221 of 14999
. Design point 13222 of 14999
. Design point 13223 of 14999
. Design point 13224 of 14999
. Design point 13225 of 14999
. Design point 13226 of 14999
. Design point 13227 of 14999
. Design point 13228 of 14999
. Design point 13229 of 14999
. Design point 13230 of 14999
. Design point 13231 of 14999
. Design point 13232 of 14999
. Design point 13233 of 14999
. Design point 13234 of 14999
. Design point 13235 of 14999
. Design point 13236 of 14999
. Design point 13237 of 14999
. Design point 13238 of 14999
. Design point 13239 of 14999
. Design point 13240 of 14999
. Design point 13241 of 14999
. Design point 13242 of 14999
. Design point 13243 of 14999
. Design point 13244 of 14999
. Design point 13245 of 14999
. Design point 13246 of 14999
. Design point 13247 of 14999
. Design point 13248 of 14999
. Design point 13249 of 14999
. Design point 13250 of 14999
. Design point 13251 of 14999
. Design point 13252 of 14999
. Design point 13253 of 14999
. Design point 13254 of 14999
. Design point 13255 of 14999
. Design point 13256 of 14999
. Design point 13257 of 14999
. Design point 13258 of 14999
. Design point 13259 of 14999
. Design point 13260 of 14999
. Design point 13261 of 14999
. Design point 13262 of 14999
. Design point 13263 of 14999
. Design point 13264 of 14999
. Design point 13265 of 14999
. Design point 13266 of 14999
. Design point 13267 of 14999
. Design point 13268 of 14999
. Design point 13269 of 14999
. Design point 13270 of 14999
. Design point 13271 of 14999
. Design point 13272 of 14999
. Design point 13273 of 14999
. Design point 13274 of 14999
. Design point 13275 of 14999
. Design point 13276 of 14999
. Design point 13277 of 14999
. Design point 13278 of 14999
. Design point 13279 of 14999
. Design point 13280 of 14999
. Design point 13281 of 14999
. Design point 13282 of 14999
. Design point 13283 of 14999
. Design point 13284 of 14999
. Design point 13285 of 14999
. Design point 13286 of 14999
. Design point 13287 of 14999
. Design point 13288 of 14999
. Design point 13289 of 14999
. Design point 13290 of 14999
. Design point 13291 of 14999
. Design point 13292 of 14999
. Design point 13293 of 14999
. Design point 13294 of 14999
. Design point 13295 of 14999
. Design point 13296 of 14999
. Design point 13297 of 14999
. Design point 13298 of 14999
. Design point 13299 of 14999
. Design point 13300 of 14999
. Design point 13301 of 14999
. Design point 13302 of 14999
. Design point 13303 of 14999
. Design point 13304 of 14999
. Design point 13305 of 14999
. Design point 13306 of 14999
. Design point 13307 of 14999
. Design point 13308 of 14999
. Design point 13309 of 14999
. Design point 13310 of 14999
. Design point 13311 of 14999
. Design point 13312 of 14999
. Design point 13313 of 14999
. Design point 13314 of 14999
. Design point 13315 of 14999
. Design point 13316 of 14999
. Design point 13317 of 14999
. Design point 13318 of 14999
. Design point 13319 of 14999
. Design point 13320 of 14999
. Design point 13321 of 14999
. Design point 13322 of 14999
. Design point 13323 of 14999
. Design point 13324 of 14999
. Design point 13325 of 14999
. Design point 13326 of 14999
. Design point 13327 of 14999
. Design point 13328 of 14999
. Design point 13329 of 14999
. Design point 13330 of 14999
. Design point 13331 of 14999
. Design point 13332 of 14999
. Design point 13333 of 14999
. Design point 13334 of 14999
. Design point 13335 of 14999
. Design point 13336 of 14999
. Design point 13337 of 14999
. Design point 13338 of 14999
. Design point 13339 of 14999
. Design point 13340 of 14999
. Design point 13341 of 14999
. Design point 13342 of 14999
. Design point 13343 of 14999
. Design point 13344 of 14999
. Design point 13345 of 14999
. Design point 13346 of 14999
. Design point 13347 of 14999
. Design point 13348 of 14999
. Design point 13349 of 14999
. Design point 13350 of 14999
. Design point 13351 of 14999
. Design point 13352 of 14999
. Design point 13353 of 14999
. Design point 13354 of 14999
. Design point 13355 of 14999
. Design point 13356 of 14999
. Design point 13357 of 14999
. Design point 13358 of 14999
. Design point 13359 of 14999
. Design point 13360 of 14999
. Design point 13361 of 14999
. Design point 13362 of 14999
. Design point 13363 of 14999
. Design point 13364 of 14999
. Design point 13365 of 14999
. Design point 13366 of 14999
. Design point 13367 of 14999
. Design point 13368 of 14999
. Design point 13369 of 14999
. Design point 13370 of 14999
. Design point 13371 of 14999
. Design point 13372 of 14999
. Design point 13373 of 14999
. Design point 13374 of 14999
. Design point 13375 of 14999
. Design point 13376 of 14999
. Design point 13377 of 14999
. Design point 13378 of 14999
. Design point 13379 of 14999
. Design point 13380 of 14999
. Design point 13381 of 14999
. Design point 13382 of 14999
. Design point 13383 of 14999
. Design point 13384 of 14999
. Design point 13385 of 14999
. Design point 13386 of 14999
. Design point 13387 of 14999
. Design point 13388 of 14999
. Design point 13389 of 14999
. Design point 13390 of 14999
. Design point 13391 of 14999
. Design point 13392 of 14999
. Design point 13393 of 14999
. Design point 13394 of 14999
. Design point 13395 of 14999
. Design point 13396 of 14999
. Design point 13397 of 14999
. Design point 13398 of 14999
. Design point 13399 of 14999
. Design point 13400 of 14999
. Design point 13401 of 14999
. Design point 13402 of 14999
. Design point 13403 of 14999
. Design point 13404 of 14999
. Design point 13405 of 14999
. Design point 13406 of 14999
. Design point 13407 of 14999
. Design point 13408 of 14999
. Design point 13409 of 14999
. Design point 13410 of 14999
. Design point 13411 of 14999
. Design point 13412 of 14999
. Design point 13413 of 14999
. Design point 13414 of 14999
. Design point 13415 of 14999
. Design point 13416 of 14999
. Design point 13417 of 14999
. Design point 13418 of 14999
. Design point 13419 of 14999
. Design point 13420 of 14999
. Design point 13421 of 14999
. Design point 13422 of 14999
. Design point 13423 of 14999
. Design point 13424 of 14999
. Design point 13425 of 14999
. Design point 13426 of 14999
. Design point 13427 of 14999
. Design point 13428 of 14999
. Design point 13429 of 14999
. Design point 13430 of 14999
. Design point 13431 of 14999
. Design point 13432 of 14999
. Design point 13433 of 14999
. Design point 13434 of 14999
. Design point 13435 of 14999
. Design point 13436 of 14999
. Design point 13437 of 14999
. Design point 13438 of 14999
. Design point 13439 of 14999
. Design point 13440 of 14999
. Design point 13441 of 14999
. Design point 13442 of 14999
. Design point 13443 of 14999
. Design point 13444 of 14999
. Design point 13445 of 14999
. Design point 13446 of 14999
. Design point 13447 of 14999
. Design point 13448 of 14999
. Design point 13449 of 14999
. Design point 13450 of 14999
. Design point 13451 of 14999
. Design point 13452 of 14999
. Design point 13453 of 14999
. Design point 13454 of 14999
. Design point 13455 of 14999
. Design point 13456 of 14999
. Design point 13457 of 14999
. Design point 13458 of 14999
. Design point 13459 of 14999
. Design point 13460 of 14999
. Design point 13461 of 14999
. Design point 13462 of 14999
. Design point 13463 of 14999
. Design point 13464 of 14999
. Design point 13465 of 14999
. Design point 13466 of 14999
. Design point 13467 of 14999
. Design point 13468 of 14999
. Design point 13469 of 14999
. Design point 13470 of 14999
. Design point 13471 of 14999
. Design point 13472 of 14999
. Design point 13473 of 14999
. Design point 13474 of 14999
. Design point 13475 of 14999
. Design point 13476 of 14999
. Design point 13477 of 14999
. Design point 13478 of 14999
. Design point 13479 of 14999
. Design point 13480 of 14999
. Design point 13481 of 14999
. Design point 13482 of 14999
. Design point 13483 of 14999
. Design point 13484 of 14999
. Design point 13485 of 14999
. Design point 13486 of 14999
. Design point 13487 of 14999
. Design point 13488 of 14999
. Design point 13489 of 14999
. Design point 13490 of 14999
. Design point 13491 of 14999
. Design point 13492 of 14999
. Design point 13493 of 14999
. Design point 13494 of 14999
. Design point 13495 of 14999
. Design point 13496 of 14999
. Design point 13497 of 14999
. Design point 13498 of 14999
. Design point 13499 of 14999
. Design point 13500 of 14999
. Design point 13501 of 14999
. Design point 13502 of 14999
. Design point 13503 of 14999
. Design point 13504 of 14999
. Design point 13505 of 14999
. Design point 13506 of 14999
. Design point 13507 of 14999
. Design point 13508 of 14999
. Design point 13509 of 14999
. Design point 13510 of 14999
. Design point 13511 of 14999
. Design point 13512 of 14999
. Design point 13513 of 14999
. Design point 13514 of 14999
. Design point 13515 of 14999
. Design point 13516 of 14999
. Design point 13517 of 14999
. Design point 13518 of 14999
. Design point 13519 of 14999
. Design point 13520 of 14999
. Design point 13521 of 14999
. Design point 13522 of 14999
. Design point 13523 of 14999
. Design point 13524 of 14999
. Design point 13525 of 14999
. Design point 13526 of 14999
. Design point 13527 of 14999
. Design point 13528 of 14999
. Design point 13529 of 14999
. Design point 13530 of 14999
. Design point 13531 of 14999
. Design point 13532 of 14999
. Design point 13533 of 14999
. Design point 13534 of 14999
. Design point 13535 of 14999
. Design point 13536 of 14999
. Design point 13537 of 14999
. Design point 13538 of 14999
. Design point 13539 of 14999
. Design point 13540 of 14999
. Design point 13541 of 14999
. Design point 13542 of 14999
. Design point 13543 of 14999
. Design point 13544 of 14999
. Design point 13545 of 14999
. Design point 13546 of 14999
. Design point 13547 of 14999
. Design point 13548 of 14999
. Design point 13549 of 14999
. Design point 13550 of 14999
. Design point 13551 of 14999
. Design point 13552 of 14999
. Design point 13553 of 14999
. Design point 13554 of 14999
. Design point 13555 of 14999
. Design point 13556 of 14999
. Design point 13557 of 14999
. Design point 13558 of 14999
. Design point 13559 of 14999
. Design point 13560 of 14999
. Design point 13561 of 14999
. Design point 13562 of 14999
. Design point 13563 of 14999
. Design point 13564 of 14999
. Design point 13565 of 14999
. Design point 13566 of 14999
. Design point 13567 of 14999
. Design point 13568 of 14999
. Design point 13569 of 14999
. Design point 13570 of 14999
. Design point 13571 of 14999
. Design point 13572 of 14999
. Design point 13573 of 14999
. Design point 13574 of 14999
. Design point 13575 of 14999
. Design point 13576 of 14999
. Design point 13577 of 14999
. Design point 13578 of 14999
. Design point 13579 of 14999
. Design point 13580 of 14999
. Design point 13581 of 14999
. Design point 13582 of 14999
. Design point 13583 of 14999
. Design point 13584 of 14999
. Design point 13585 of 14999
. Design point 13586 of 14999
. Design point 13587 of 14999
. Design point 13588 of 14999
. Design point 13589 of 14999
. Design point 13590 of 14999
. Design point 13591 of 14999
. Design point 13592 of 14999
. Design point 13593 of 14999
. Design point 13594 of 14999
. Design point 13595 of 14999
. Design point 13596 of 14999
. Design point 13597 of 14999
. Design point 13598 of 14999
. Design point 13599 of 14999
. Design point 13600 of 14999
. Design point 13601 of 14999
. Design point 13602 of 14999
. Design point 13603 of 14999
. Design point 13604 of 14999
. Design point 13605 of 14999
. Design point 13606 of 14999
. Design point 13607 of 14999
. Design point 13608 of 14999
. Design point 13609 of 14999
. Design point 13610 of 14999
. Design point 13611 of 14999
. Design point 13612 of 14999
. Design point 13613 of 14999
. Design point 13614 of 14999
. Design point 13615 of 14999
. Design point 13616 of 14999
. Design point 13617 of 14999
. Design point 13618 of 14999
. Design point 13619 of 14999
. Design point 13620 of 14999
. Design point 13621 of 14999
. Design point 13622 of 14999
. Design point 13623 of 14999
. Design point 13624 of 14999
. Design point 13625 of 14999
. Design point 13626 of 14999
. Design point 13627 of 14999
. Design point 13628 of 14999
. Design point 13629 of 14999
. Design point 13630 of 14999
. Design point 13631 of 14999
. Design point 13632 of 14999
. Design point 13633 of 14999
. Design point 13634 of 14999
. Design point 13635 of 14999
. Design point 13636 of 14999
. Design point 13637 of 14999
. Design point 13638 of 14999
. Design point 13639 of 14999
. Design point 13640 of 14999
. Design point 13641 of 14999
. Design point 13642 of 14999
. Design point 13643 of 14999
. Design point 13644 of 14999
. Design point 13645 of 14999
. Design point 13646 of 14999
. Design point 13647 of 14999
. Design point 13648 of 14999
. Design point 13649 of 14999
. Design point 13650 of 14999
. Design point 13651 of 14999
. Design point 13652 of 14999
. Design point 13653 of 14999
. Design point 13654 of 14999
. Design point 13655 of 14999
. Design point 13656 of 14999
. Design point 13657 of 14999
. Design point 13658 of 14999
. Design point 13659 of 14999
. Design point 13660 of 14999
. Design point 13661 of 14999
. Design point 13662 of 14999
. Design point 13663 of 14999
. Design point 13664 of 14999
. Design point 13665 of 14999

In [20]:
all_data[fam]['modes']

,dp_no,mode_no,freq,rel_dev,mean_in_disp,mean_out_disp,mode_gain,mode_mac
0,13000,25,10465.842,569.52522,0.005,0.002,0.39670,4.742000e-07
1,13000,26,10562.594,836.98470,0.003,0.001,0.30999,1.666200e-06
2,13000,27,10690.752,17.26705,-0.017,-0.050,3.01429,2.423648e-02
3,13000,28,10697.640,52.19333,0.005,0.016,3.36536,3.666563e-03
4,13000,29,10756.505,360.01716,-0.000,-0.002,12.45974,2.780962e-04
...,...,...,...,...,...,...,...,...
143787,14999,96,23755.595,1197.96751,-0.001,-0.001,0.61500,2.777900e-06
143788,14999,97,23787.878,1157.28740,-0.002,0.001,0.46326,1.735720e-05
143789,14999,98,23935.293,74.60470,-0.189,-0.016,0.08659,2.212621e-02
143790,14999,99,23998.575,1283.13848,-0.007,-0.001,0.12111,4.274050e-05
143791,14999,100,24052.693,191.95537,-0.001,0.004,3.22201,3.146583e-04

In [21]:
all_data[fam]['nodes']

        dp_no  node_no     x_coord  y_coord    z_coord
0       13000        1 -117.730000      0.0 -68.350000
1       13000       10 -117.730000      0.0  68.350000
2       13000       11 -117.730000      0.0  48.821429
3       13000       12 -117.730000      0.0  29.292857
4       13000       13 -117.730000      0.0   9.764286
...       ...      ...         ...      ...        ...
827433  14999    11377 -103.647830      0.0 -22.727667
827434  14999    11389   -9.320281      0.0  45.639013
827435  14999    11393   -1.321685      0.0 -57.650627
827436  14999    11402   23.855593      0.0  52.006522
827437  14999    11406  -24.903201      0.0  47.108686

[827438 rows x 5 columns]

In [22]:
all_data[fam]['defs']

,dp_no,node_no,mode25,mode26,mode27,mode28,mode29,mode30,mode31,mode32,...,mode91,mode92,mode93,mode94,mode95,mode96,mode97,mode98,mode99,mode100
0,13000,1,-0.152545,0.103005,-0.431871,-0.153478,-0.001373,-0.539620,0.060917,0.260966,...,-0.195948,-0.240255,0.017833,0.043073,-0.184019,-0.524422,0.518505,-0.179127,-0.528551,0.266107
1,13000,10,-0.067810,-0.103795,-0.447014,-0.168769,-0.017965,-0.525715,-0.061969,-0.263528,...,0.186421,-0.232691,0.002575,-0.036398,-0.425681,-0.359304,-0.518142,0.173874,-0.534474,-0.255294
2,13000,11,-0.160900,-0.171439,-0.329279,-0.145528,0.022937,-0.280102,0.111420,-0.179336,...,0.240831,-0.293380,0.282648,0.099466,-0.168188,-0.564537,-0.367381,-0.026794,-0.425581,-0.545231
3,13000,12,-0.332519,-0.167854,-0.057402,-0.033475,0.045938,0.101501,0.231889,-0.116478,...,0.095839,-0.288376,0.440265,0.192407,0.306934,-0.194746,-0.054345,-0.254571,0.158219,-0.437644
4,13000,13,-0.453488,-0.067816,0.184482,0.114725,0.025156,0.365993,0.095391,-0.048896,...,-0.041690,-0.223657,0.127819,0.090189,0.458551,0.476439,0.001012,-0.087011,0.721276,-0.086181
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
827433,14999,11377,0.192485,-0.016552,0.119268,0.247655,0.076629,0.154211,0.223689,0.116655,...,-0.356012,0.050855,-0.155442,-0.011102,-0.001508,-0.254624,-0.454500,-0.172505,0.003866,-0.165610
827434,14999,11389,-0.086807,0.126193,-0.008377,0.007707,-0.059282,-0.231126,-0.016740,0.059327,...,0.419622,-0.134512,0.173201,0.019890,0.006921,-0.050741,-0.090967,-0.117269,-0.002702,0.173475
827435,14999,11393,-0.004609,-0.018034,0.000547,-0.001599,0.006163,-0.300405,-0.020531,-0.054709,...,0.406048,-0.031369,-0.012084,-0.010106,-0.005405,0.062855,0.018986,-0.213393,-0.013875,0.031907
827436,14999,11402,-0.063549,-0.247389,0.006207,-0.075778,0.186390,-0.215566,0.032333,0.034665,...,0.285050,0.250968,-0.406350,-0.012173,-0.014095,-0.099083,0.110335,-0.131153,-0.087707,0.077845
827437,14999,11406,-0.070072,0.247441,-0.020644,0.061670,-0.205018,-0.172879,-0.034619,0.061216,...,0.260466,-0.258135,0.407823,0.034248,0.033161,-0.047496,-0.111363,-0.101880,0.096757,0.161044